---
# This playbook installs pycharm
# unfortunately there're no fedora / rhel packages so
# we download zip and unarchive it
# in order to update your current installation you have to remove it manually
# or invoke playbook with "-e update_apps=true" or simply update from within
# pycharm
# After update you'll probably have to run application manually from
# ./bin/pycharm.sh and re - generate desktopr entry / cmd - launcher (Tools
# -> Create Desktop Entry) and re - import settings from ~/.PycharmXXX 
# directory

- name: Check if there is any old installation
  stat: path="{{ local_soft_dir }}/pycharm"
  register: pycharm_state

- block:
  - name: Download package
    get_url: >
      dest={{ temp_dir }}/pycharm.tar.gz
      url="https://download.jetbrains.com/python/pycharm-community-2018.2.4.tar.gz"

  - name: Ensure Pycharm directory is removed
    file: >
      path={{ local_soft_dir }}/Pycharm
      state=absent

  - name: Extract archive
    unarchive: >
      src={{ temp_dir }}/pycharm.tar.gz
      dest={{ local_soft_dir }}/
      group={{ group }}
      owner={{ user }}
  when: pycharm_state.stat.exists == false or update_apps | default('') != ''

# details aboout this operation: https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit
- name: Increase inotify limit
  sysctl:
      sysctl_file: /etc/sysctl.d/pycharm.conf
      name: fs.inotify.max_user_watches
      value: 524288
      reload: yes
      state: present
