---
# This playbook installs 1password CLI client
# (see https://app-updates.agilebits.com/product_history/CLI)
# we download zip and unarchive it
# in order to update your current installation you have to remove it manually
# or invoke playbook with "-e update_apps=true"

- name: Check if there is any old installation
  stat: path="{{ local_bin_dir }}/op"
  register: op_state

- block:
  - name: Download package
    get_url:
      dest: "{{ temp_dir }}/op.zip"
      url: "https://cache.agilebits.com/dist/1P/op/pkg/v0.5.1/op_linux_amd64_v0.5.1.zip"

  - name: Ensure 1password binary is removed
    file:
      path: "{{ local_bin_dir }}/op"
      state: absent

  - name: Extract archive
    unarchive:
      src: "{{ temp_dir }}/op.zip"
      dest: "{{ local_bin_dir }}/"
      group: "{{ group }}"
      owner: "{{ user }}"

  when: op_state.stat.exists == false or update_apps | default('') != ''
